### ISSUE TITLE
Local wifi sync?

### ISSUE THREAD

**Issue by wjmt3** [buttercup/dossier#10]
I'd like to be able to sync data between my phone and computer without it leaving my local network.

**Comment by perry-mitchell** [comment]
You could host a WebDAV service in your LAN and use that to access your vault. Not sure that it’s anything buttercup should provide. If we did, it’d most likely just be a WebDAV wrapper.. would these then still be useful?

**Comment by perry-mitchell** [comment]
We may also release a self-hosted server at some stage, which could handle such a situation. For now I'll close this but I'd be happy to see it supported via community contribution.
