### ISSUE TITLE
Describe support for "Google Drive" consistently

### ISSUE THREAD

**Issue by henkoberholzer** [buttercup/dossier#12]
On the page "/roadmap/CLOUD_SERVICES.md", support for Google Drive is both listed under "Supported solutions" as well as under "Blocked/Pending solutions". If this is not a mistake then some additional clarification might be required.

PS: Thank you for creating Buttercup :-)

**Comment by perry-mitchell** [comment]
It's supported by our browser and mobile apps, and will soon be released on desktop under buttercup/buttercup-desktop#756. I'll update the docs to mirror this.
