### ISSUE TITLE
Freeform notes with carrige returns

### ISSUE THREAD

**Issue by calmandpatient** [buttercup/dossier#13]
I saw the closed issue on notes but am not sure if it covers this functionality.

It would be helpful to be able to store multi line notes with CR/LF in them. At the moment all notes appear to need to be only on one continuous line which makes less readable.

I am aware it is possible to add multiple new fields but this can be a bit long winded.

Thanks!

**Comment by perry-mitchell** [comment]
Currently supported in the browser extension, and will be rolled out to other apps soon.

**Comment by calmandpatient** [comment]
Thanks Perry - very much appreciated
