### ISSUE TITLE
Feature Request: Custom password Fields

### ISSUE THREAD

**Issue by claywd** [buttercup/dossier#17]
Would be great if we could determine what extra fields were sensitive helping protect what information shows up on a screen if at all. Direct copy secret to clipboard for more than just password would be nice.

**Comment by perry-mitchell** [comment]
Hello! This is already supported in the browser extension, and will soon be available in our other apps.

**Comment by perry-mitchell** [comment]
If you could clarify your second point and put it in a new issue that’d be great, if you feel that it’s not covered elsewhere.
