### ISSUE TITLE
Feature Request: Direct Copy Secret to Clipboard

### ISSUE THREAD

**Issue by claywd** [buttercup/dossier#18]
So in general, whether its a username, pin code, serial etc. It would be great if we could attach a copy button to every field so instead of highlighting the data to be copied and then executing the cmd + c or right click +copy we could click the copy button and away we go.

**Comment by TargetCrafter** [comment]
This is possible for all the fields. I don't lnow when this was added, but it's in there for sure..
https://imgur.com/a/k8BPW6s

**Comment by perry-mitchell** [comment]
@Claywd As @TargetCrafter said it is available in the new UI, currently available in the browser extension (soon coming to desktop as well):

![image](https://user-images.githubusercontent.com/3869469/63600685-b14b1980-c5cc-11e9-9c6e-781cfee1ed8f.png)

It's also available in the current desktop UI:

![image](https://user-images.githubusercontent.com/3869469/63600722-c58f1680-c5cc-11e9-8430-0719a56e9fdf.png)
