### ISSUE TITLE
Browser Support: Internet Explorer 11 And Edge

### ISSUE THREAD

**Issue by GitDaan** [buttercup/dossier#20]
Add on for Internet Explorer 11?
Edge - not sure what Microsoft's road map is for the Edge browser but if it does become the sole browser then an add-on will be needed.

**Comment by TargetCrafter** [comment]
It looks like MS Edge support is on the roadmap, but i'm guessing that it will be removed due to the fact that Microsoft is working on a chromium based version of MS Edge. This means that the Google Chrome version will work in the new version of MS Edge.

**Comment by perry-mitchell** [comment]
Correct @TargetCrafter - Ideally we wouldn't re-release for MS Edge. If we have to it'll still be easy enough due to the fact that the same codebase should work.

We will not be supporting IE.
