### ISSUE TITLE
Microsoft Edge is now chromium based, extensions no longer need to be modified

### ISSUE THREAD

**Issue by superusercode** [buttercup/dossier#23]
There is no work to port the extensions since the new edge is based on chrome. All users on Windows/macOS (and Linux in the near future) are already able to install it from the chrome web store when prompted to enable downloads from the CWS. The extension submission process is detailed at https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension

**Comment by superusercode** [comment]
So now that there won't be any work necessary to port the extension, could a listing on the MEA store be expected sooner than originally planned on the roadmap?

**Comment by perry-mitchell** [comment]
We’re actually already live: https://microsoftedge.microsoft.com/addons/detail/jjcapdgcepplkhhfaopdoknkccjnlmlf 😁

**Comment by superusercode** [comment]
my bad, was confused since it's still marked as planned on the roadmap and only the chrome version is offered to me on the site. 
![image](https://user-images.githubusercontent.com/60588434/75448426-2fe89100-5939-11ea-9be5-c17e9d3a6287.png)
