### ISSUE TITLE
Export archives in csv format

### ISSUE THREAD

**Issue by fmommeja** [buttercup/dossier#3]
One important feature is missing to Buttercup: exporting all archive datas in an open format like csv.
Now, once the archives datas are entered in Buttercup, they are only available in the .bcup 'proprietary' format… which is not compatible with the OpenSource philosophy.  ;)

Could you please provide such a functionnality to your users?

**Comment by rebootit** [comment]
I agree. I'm a bit disappointed about this point; this is completely the opposite of open source.
I don't recommand using this app!!

**Comment by perry-mitchell** [comment]
Please keep these conversations constructive. We haven’t added it as we haven’t had time yet.. it’s open source so YOU can also help out.

**Comment by GabrielFotoPoto** [comment]
Hi everyone, I think this is a necessary feature especially with the arrival of the GDPR, it could even highlight the project and promote its adoption by many people

**Comment by perry-mitchell** [comment]
Closing in favour of buttercup/buttercup-core#211
