### ISSUE TITLE
Unable to unlock vault in Brave web browser

### ISSUE THREAD

**Issue by barju6693** [buttercup/dossier#36]
In Brave web browser, when I try to enter the password to unlock the vault, the field to introduce the password is not visible and can't be unlocked.

![image](https://github.com/buttercup/dossier/assets/17111636/ee992527-1e17-4df4-8d91-8e95ff685017)

In the console I get this message:
```
Error handling response: Error: Redux state sync failed: The message port closed before a response was received.
    at handleSendMessageResponse (chrome-extension://heflipieckodmcppbnembejjmabajjjj/vendors.js:531:481034)
```

**Comment by perry-mitchell** [comment]
Wrong repo. Should be on the browser extension repository.
