### ISSUE TITLE
Clear clipboard after 30sec

### ISSUE THREAD

**Issue by jonlabr** [buttercup/dossier#4]
Is it possible to clear clipboard 30sec after copy a password?

**Comment by perry-mitchell** [comment]
Hi @jonlabr - This was added in buttercup/buttercup-desktop#2.

If it's not working for you, it'd be great if you could open a bug in the appropriate repo. Cheers!

Edit: ~~Just confirming with my colleague that we haven't had regression on this front.~~ Confirmed that it's set to 15sec in the code.
