### ISSUE TITLE
[Desktop] Allow quick search in the whole archive

### ISSUE THREAD

**Issue by dcfranca** [buttercup/dossier#5]
Would be nice to be able to quickly search your credentials.
This could be done by adding a search bar on top of the list of entries.

![deepinscreenshot_select-area_20180531094911](https://user-images.githubusercontent.com/86538/40769302-eec6931a-64b7-11e8-8b68-ad570da101d6.png)

**Comment by perry-mitchell** [comment]
It's already possible by using `Ctrl+F` in the desktop application.. is this not what you mean?

**Comment by dcfranca** [comment]
ohh, true... I think it makes sense this being on the Edit Menu, not in the File.
But anyway it is what I was looking for.
Thanks

**Comment by perry-mitchell** [comment]
Excellent! Yes I somewhat agree.. feel free to create an issue if you feel the location is wrong.
