### ISSUE TITLE
Overall roadmap doc seems to be out of date?

### ISSUE THREAD

**Issue by HerbCaudill** [buttercup/dossier#8]
https://github.com/buttercup/roadmap/blob/master/roadmap/OVERALL.md

I came to this repo to get a sense of where the project is at, and this file was last updated 1.5 years ago. It shows the desktop app as being in alpha, the mobile app as 'TBA', etc.

**Comment by perry-mitchell** [comment]
This will be partially fixed by #7..

**Comment by perry-mitchell** [comment]
Currently reworking this.
